name: nightmare_tool_cli

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: "1.6.0"
  dio: ^3.0.3
  ffi: ^1.0.0
  custom_log:
    git:
      url: https://github.com/nightmare-space/custom_log
      ref: dart
